### ISSUE TITLE
http://mathema.tician.de/software/pudb has gone 404

### ISSUE THREAD

**Issue by jalanb** [inducer/pudb#136]
The URL "http://mathema.tician.de/software/pudb" results in a 404 error

The URL is shown in the banner on GitHub. It was also the first link on the wiki page at http://wiki.tiker.net/PuDB, where I updated it to "http://pypi.python.org/pypi/pudb" as that is the URL listed as homepage in PyPi

**Comment by inducer** [comment]
Thanks for the report. The URL no longer 404s.
