### ISSUE TITLE
I want to see _private members, and not methods

### ISSUE THREAD

**Issue by nedbat** [inducer/pudb#137]
When I examine "self" in the Variables pane, by default it shows me all the methods, which are not useful to me.  And it won't show `_private` names.  I can use "*" to show them, but now I also get `__dunder__` methods which are even more noise and clutter that aren't helping me.

Is there some mode or command I'm missing that lets me see my data without being obscured by methods?

**Comment by inducer** [comment]
Thanks for the suggestion. I'd love to take a PR that addresses this. Here are the relevant bits of code:

* [State](/inducer/pudb/blob/master/pudb/var_view.py#L47): `show_private_members` probably should become a tri-state: No, private, and everything
* [Rendering](/inducer/pudb/blob/master/pudb/var_view.py#L367)
* [UI 1](/inducer/pudb/blob/1b3ee789081f954f99144f3d1bb6f213120b5cb6/pudb/debugger.py#L766) [UI 2](/inducer/pudb/blob/1b3ee789081f954f99144f3d1bb6f213120b5cb6/pudb/debugger.py#L818)

**Comment by nedbat** [comment]
I guess I was imagining the 'm' key would toggle methods or not.  Are you OK with changing the default behavior?  I would prefer that methods not be shown by default.  If so, then '*' could work as you say:  public, public+private, everything.

**Comment by inducer** [comment]
Either of those would work for me.

**Comment by inducer** [comment]
Continuing in #138.
