### ISSUE TITLE
Issues with colors and themes

### ISSUE THREAD

**Issue by arturhoo** [inducer/pudb#156]
I've been trying to get pudb to work nicely with iTerm2, theme-wise and for some reason I'm failing hard. Has anyone managed to render the correct colors when using both?

![image](https://cloud.githubusercontent.com/assets/119276/10921125/f67602ae-825a-11e5-9694-f28d41d40ab5.png)

I've tried changing between auto/raw/curses to no avail. Everything works fine on Terminal.app though.

**Comment by asmeurer** [comment]
I use iTerm2 and it all works for me. What is your $TERM?

**Comment by arturhoo** [comment]
Hi @asmeurer, here it is
```
~ $ echo $TERM
xterm-256color
```

**Comment by amigrave** [comment]
Maybe you've defined some custom colors in your profile ?

[My theme](https://github.com/inducer/pudb/pull/154) renders ok on iTerm2 (OSX) and Terminator ([vte](https://launchpad.net/vte) on Linux) both using `$TERM=xterm-256color`.
I have custom colors in both terminals but it renders ok on stock setup too.

Out of curiosity, could you post a screenshot of the `agr-256` theme on your setup ?

**Comment by asmeurer** [comment]
What versions of iTerm2 and urwid are you using?

**Comment by arturhoo** [comment]
I do have a base16 non-256 colorspace version loaded on iTerm2. Here is the agr-256 theme:

![image](https://cloud.githubusercontent.com/assets/119276/10944390/1406391a-8300-11e5-92c4-ac48e742877f.png)

I'm using iTerm2 Build 2.9.20151001, but I tested it on the latest stable Build 2.1.4 with the same results. Urwid version is `urwid==1.3.1`

**Comment by asmeurer** [comment]
> I do have a base16 non-256 colorspace version loaded on iTerm2. Here is the agr-256 theme:

What does that mean? What happens if you create a new profile in iTerm2 with the default settings and run PuDB in that?

**Comment by arturhoo** [comment]
I feel silly now, but changing to the 'Dark Background' default theme worked! It is odd, because I definitely tried that and a handful of other things yesterday, so I'll probably never know what was wrong. Anyway, thanks for the support and sorry about the waste of time! Feel free to close this issue.

**Comment by asmeurer** [comment]
I think there's no bug in PuDB here, so I'm closing.
