### ISSUE TITLE
Building TextCanvas with existing text, attr and cs splits on bytes, not characters

### ISSUE THREAD

**Issue by pquentin** [inducer/pudb#172]
(I've cross-posted this issue at https://github.com/urwid/urwid/issues/182)

I'm using Python 3. The variables on the right are displayed in a `urwid.TextCanvas`. pudb uses `TextCanvas` after having wrapped the lines himself, which is why it prepares `text`, `attr` and `cs` himself. Unfortunately, TextCanvas somehow wraps the lines again, but it wrap bytes, not an unicode string. As a result, Unicode codepoints that are encoded using two bytes in UTF-8 can be split in two. The code below reproduces the issue:

```
from urwid import TextCanvas

text=u'aaaaaé'
cols=len(text)

c = TextCanvas(
    text=[text.encode('UTF-8')],
    attr=[[('var value', cols)]],
    cs=[[(None, cols)]],
    maxcol=cols
)

print(list(c.content()))
```

It prints `[[('var value', None, b'aaaaa\xc3'), (None, None, b'\xa9')]]` while I would have expected `[[('var value', None, b'aaaaa\xc3\xa9')]]`

pudb crashes nearly every day due to this bug. Is pudb using urwid incorrectly, or is this a urwid bug? Thank you!

**Comment by asmeurer** [comment]
What's an example that makes PuDB crash? I tried running it with `text=u'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaé'`, which text wraps just fine.

**Comment by pquentin** [comment]
What did you run with `text=u'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaé'`? The code I pasted above? It continues to split in two: it gives `[[('var value', None, b'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\xc3'), (None, None, b'\xa9')]]`. When urwid prints this, it first tries to decode this from UTF-8, and fails because "\xc3" is invalid UTF-8. The correct code is:

```

from urwid import TextCanvas

text=u'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaé'
charcols=len(text)
bytecols=len(text.encode('UTF-8'))

c = TextCanvas(
    text=[text.encode('UTF-8')],
    attr=[[('var value', bytecols)]],
    cs=[[(None, bytecols)]],
    maxcol=charcols
)

print(list(c.content()))
```

But that's harder to fix in `make_canvas`. Fixing this bug would also fix the ["bleeding issue" reported by bukzor](https://github.com/inducer/pudb/issues/111#issuecomment-37262145).

**Comment by pquentin** [comment]
A simple way to reproduce this:

```
text = "é" * 1000
import pudb; pu.db
```
gives

```
$ python3 repro.py
Traceback (most recent call last):
  File "repro.py", line 2, in <module>
    import pudb; pu.db
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/bdb.py", line 52, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/bdb.py", line 93, in dispatch_return
    self.user_return(frame, arg)
  File "/Users/quentin/Code/pudb/pudb/debugger.py", line 385, in user_return
    self.interaction(frame)
  File "/Users/quentin/Code/pudb/pudb/debugger.py", line 339, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/Users/quentin/Code/pudb/pudb/debugger.py", line 2059, in call_with_ui
    return f(*args, **kwargs)
  File "/Users/quentin/Code/pudb/pudb/debugger.py", line 2272, in interaction
    self.event_loop()
  File "/Users/quentin/Code/pudb/pudb/debugger.py", line 2231, in event_loop
    self.screen.draw_screen(self.size, canvas)
  File "/Users/quentin/.virtualenvs/pudb/lib/python3.5/site-packages/urwid/raw_display.py", line 838, in draw_screen
    l = l.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 43: unexpected end of data
```

at any width (< 1000, obviously).

**Comment by inducer** [comment]
Yep, that's a bug. Would be happy to take a patch.

**Comment by pquentin** [comment]
Certainly not perfect, but I gave it a try at https://github.com/inducer/pudb/pull/174. Feel free to rework partially/completely my patch. No worries for attribution.
