### ISSUE TITLE
How Do I use Pudb In Ipython Notebook

### ISSUE THREAD

**Issue by xylophone234** [inducer/pudb#176]
in ipython
import pudb.ipython
%pudb script.py
it works well.
But in ipython notebook,
%pudb createtree0.py

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-a10b15855802> in <module>()
----> 1 get_ipython().magic(u'pudb createtree0.py')

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2161         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2162         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2163         return self.run_line_magic(magic_name, magic_arg_s)
   2164 
   2165     #-------------------------------------------------------------------------

/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2082                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2083             with self.builtin_trap:
-> 2084                 result = fn(*args,**kwargs)
   2085             return result
   2086 

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/ipython.pyc in pudb(line)
    106 
    107         from pudb import runscript
--> 108         runscript(path, args)
    109     register_line_magic(pudb)
    110 

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/__init__.pyc in runscript(mainpyfile, args, pre_run, steal_output)
     82         except:
     83             dbg.post_mortem = True
---> 84             dbg.interaction(None, sys.exc_info())
     85 
     86         while True:

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/debugger.pyc in interaction(self, frame, exc_tuple, show_exc_dialog)
    337 
    338         self.ui.call_with_ui(self.ui.interaction, exc_tuple,
--> 339                 show_exc_dialog=show_exc_dialog)
    340 
    341     def get_stack_situation_id(self):

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/debugger.pyc in call_with_ui(self, f, *args, **kwargs)
   2057         self.show()
   2058         try:
-> 2059             return f(*args, **kwargs)
   2060         finally:
   2061             self.hide()

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/debugger.pyc in interaction(self, exc_tuple, show_exc_dialog)
   2257         if self.debugger.post_mortem:
   2258             if show_exc_dialog and exc_tuple is not None:
-> 2259                 self.show_exception_dialog(exc_tuple)
   2260 
   2261             caption.extend([

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/debugger.pyc in show_exception_dialog(self, exc_tuple)
   2003                     buttons_and_results=[
   2004                         ("OK", True),
-> 2005                         ("Save traceback", "save"),
   2006                         ])
   2007 

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/debugger.pyc in dialog(self, content, buttons_and_results, title, bind_enter_esc, focus_buttons, extra_bindings)
   1976         w = Attr(w, "background")
   1977 
-> 1978         return self.event_loop(w)[0]
   1979 
   1980     @staticmethod

/usr/local/lib/python2.7/dist-packages/pudb-2016.1-py2.7.egg/pudb/debugger.pyc in event_loop(self, toplevel)
   2230                 canvas = toplevel.render(self.size, focus=True)
   2231                 self.screen.draw_screen(self.size, canvas)
-> 2232                 keys = self.screen.get_input()
   2233 
   2234                 for k in keys:

/usr/local/lib/python2.7/dist-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.pyc in get_input(self, raw_keys)
    323 
    324         self._wait_for_input_ready(self._next_timeout)
--> 325         keys, raw = self.parse_input(None, None, self.get_available_raw_input())
    326 
    327         # Avoid pegging CPU at 100% when slowly resizing

/usr/local/lib/python2.7/dist-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.pyc in get_available_raw_input(self)
    425         implementation; you can safely ignore it if you implement your own.
    426         """
--> 427         codes = self._get_gpm_codes() + self._get_keyboard_codes()
    428 
    429         if self._partial_codes:

/usr/local/lib/python2.7/dist-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.pyc in _get_keyboard_codes(self)
    499         codes = []
    500         while True:
--> 501             code = self._getch_nodelay()
    502             if code < 0:
    503                 break

/usr/local/lib/python2.7/dist-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.pyc in _getch_nodelay(self)
    633 
    634     def _getch_nodelay(self):
--> 635         return self._getch(0)
    636 
    637 

/usr/local/lib/python2.7/dist-packages/urwid-1.3.1-py2.7-linux-x86_64.egg/urwid/raw_display.pyc in _getch(self, timeout)
    543                 self.gpm_event_pending = True
    544         if self._term_input_file.fileno() in ready:
--> 545             return ord(os.read(self._term_input_file.fileno(), 1))
    546         return -1
    547 

TypeError: ord() expected a character, but string of length 0 found

**Comment by inducer** [comment]
There's no support for Ipython/Jupyter Notebook.
