### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by pquentin** [inducer/pudb#188]
A number of nice fixes have been committed since the last release. Is a new release planned soon?

Thanks!

**Comment by asmeurer** [comment]
Don't hold off on a release on account of #186. It might be a bit before I finish it up.

**Comment by inducer** [comment]
2016.2, hot off the presses. Just for you. :)

**Comment by pquentin** [comment]
Thank you @inducer!

(It looks like it's called 2016.1 on git/GitHub and 2016.2 on PyPI)
