### ISSUE TITLE
OSX - going into console and typing causes draw issues (console is losing focus?)

### ISSUE THREAD

**Issue by mlubimow** [inducer/pudb#191]
When debugger window is opened, after I go to console and I try to type something, I'm getting issues like this:

http://i.imgur.com/zPjyAMP.png

After it gets corrupted, it looks like Pudb is not getting any events. If I press for example CTRL-X, it just prints ^X in console. If I press Enter then, it goes to code window but still I cant see it because of drawing issues (but I know it does go to code because I'm able to press Q and Enter to exit from debugger).

After some investigations I found that importing **readline** module at the top of debugger.py file fixes the issue (I found it because going to ipython console was fixing the issue, so step by step I found that this is somehow fixing the issue).

So, easy fix is to add **import readline**, but its indirect solution.

**Comment by inducer** [comment]
Pudb relies on something called the alternate screen to be supported in your
terminal. From your screenshot, it does not look like that's the case. What
terminal emulator are you using?

**Comment by mlubimow** [comment]
ITerm2 3.0+, with
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.4.0), with
environment variable TERM=xterm-color

**Comment by inducer** [comment]
@asmeurer, any ideas?

**Comment by asmeurer** [comment]
This is the same issue as https://github.com/inducer/pudb/issues/166. 

That's interesting that importing readline makes a difference. It's already imported [here](https://github.com/inducer/pudb/blob/255f318fbb61f008fe7cffd4e5df1fc31c84211c/pudb/shell.py#L21). 

Let's continue the discussion at #166.
