### ISSUE TITLE
Enable `from __future__ import absolute_import` to work around bug on non case-sensitive file systems

### ISSUE THREAD

**Issue by rory-geoghegan-ecometrica** [inducer/pudb#194]
I hit a bug where in python 2.7, the `pudb/shell.py` module will try to import (innocently) the IPython package (to set the `HAVE_IPYTHON` variable), but actually import the `pudb/ipython.py` module instead, because my filesystem is case-insensitive inside my docker/docker-machine setup and it is treating `import IPython` as a relative import to the `pudb` package.

The most visible issue is my case-insensitive file-system, but also python 2.7 is trying to do a relative import in this case, while it really should not, as it does not by default in python 3.

Can we add the `from __future__ import absolute_import` either to just that module or to every module? According to [the pep](https://docs.python.org/2.5/whatsnew/pep-328.html), it should be supported by the python 2.6+ versions you support in pudb.

What would be easiest for you? Should I create a pull request?

**Comment by inducer** [comment]
PR sounds good.

**Comment by asmeurer** [comment]
I personally prefer to put `from __future__ import absolute_import, division, print_function` at the top of every file to avoid any possible issues like this.

**Comment by inducer** [comment]
Also fine by me, now that 2.5 is no longer an issue.

**Comment by rory-geoghegan-ecometrica** [comment]
Done: https://github.com/inducer/pudb/pull/195
