### ISSUE TITLE
Change size of command line

### ISSUE THREAD

**Issue by kiddick** [inducer/pudb#206]
Is it possible to change that height?
![image](https://cloud.githubusercontent.com/assets/9250239/20750633/5ce89128-b711-11e6-8c4f-f651dbf6b6c3.png)

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

Try -/= while the output is focused.

**Comment by asmeurer** [comment]
I was wondering this yesterday. I was expecting [ and ] to resize it since that's how it works in the right panel.

**Comment by inducer** [comment]
Both -/= and [/] do something in the right panel. :)

**Comment by asmeurer** [comment]
Yes, but it's backwards in the command line. I expected [ and ] to grow it vertically.

**Comment by inducer** [comment]
The point of view that makes it consistent is that -/= resizes vs the main code view.
