### ISSUE TITLE
Monokai Theme

### ISSUE THREAD

**Issue by epmoyer** [inducer/pudb#207]
I created a Monokai theme for PuDB (https://github.com/epmoyer/pudb-theme-monokai). Would you be interested in a pull request that adds Monokai to the built-in-themes? Or do you have a different vision for aggregating custom themes over time (like putting them in a themes directory?)

Cannonical Monokai colorizes some source elements which are not exposed by the current palette API (like the "def" statement, and function arguments).  Would you be interested in a pull request that exposes a couple new source elements such that Monokai could be styled more faithfully?

I've fallen in love with PuDB; thanks for all your hard work! And thanks for supporting custom themes.

**Comment by jeffwidman** [comment]
Personally, as a user I'd like to see both of these--I'm a fan of Monokai, plus colorizing the other source elements.

**Comment by asmeurer** [comment]
The current theme list is short, and Monokai is popular. I would go ahead and add it. Also fine with more complete lexing.

**Comment by inducer** [comment]
Both sound good. Submit away.

**Comment by inducer** [comment]
(And thanks for offering to contribute!)

**Comment by epmoyer** [comment]
Status report:

I've been successful at extracting the necessary tokens from Pygments to implement a faithful representation of Monokai (with the exception of function arguments).  It's not ready for prime-time yet, but I thought I'd post a quick screenshot comparison of the current Monokai rendering in pudb vs. Sublime.  I decided to implement both an ANSII color and Xterm color version (the ANSII version is shown).

The remaining hurdle is to see if I can't detect function arguments somehow (Monokai colors them orange).  Pygments does not tokenize function arguments in any special way, so a small bit of context sensitive parsing will be required to tease them out.  Feeling bullish.

I don't want to push the branch yet because the current changes have side effects on the legacy styles and I haven't fixed that yet. 

<img width="1180" alt="monokai_progress" src="https://cloud.githubusercontent.com/assets/136718/21082472/1c632a40-bf91-11e6-85a8-a96cb7afc9de.png">

Cheers!

**Comment by epmoyer** [comment]
I am closing this issue.  Pull request submitted.

**Comment by jeffwidman** [comment]
Just a thought: 
The more typical workflow I've seen in open source projects on github is to leave the issue open and in the PR add the words "Fix #207". Github will auto-crosslink the issue/PR and when/if the PR is accepted Github will automatically mark the issue as closed. It help decouple the high-level product design/engineering architecture discussion in the issue from the line-by-line engineer implementation discussion of the PR.

**Comment by epmoyer** [comment]
Excellent; thanks Jeff!
