### ISSUE TITLE
Trying to interrupt a different thread prints a warning

### ISSUE THREAD

**Issue by cdman** [inducer/pudb#212]
Tested with Python 3.5.2 and 2.7.12

Sample program:

```python
import threading


class Foo(threading.Thread):
  def run(self):
    import pudb; pu.db

Foo().start()
```

pudb version: 2016.2

Error:

```
/pudb/__init__.py:201: UserWarning: setting interrupt handler on signal 2 failed: Traceback (most recent call last):
  File "/tmp/foo/env/local/lib/python2.7/site-packages/pudb/__init__.py", line 195, in set_interrupt_handler
    signal.signal(interrupt_signal, _interrupt_handler)
ValueError: signal only works in main thread
```

signal.signal only working in the main thread is well documented (https://docs.python.org/2/library/signal.html#signal.signal). We can detect if the current thread is the main thread and just skip setting the signal handler (`isinstance(threading.current_thread(), threading._MainThread)` - from http://stackoverflow.com/a/23207116), but I don't know what functionality we loose if we do that.

**Comment by inducer** [comment]
Thanks for the report! We lose being able to press Ctrl-C (which is fine--since that wasn't going to work anyway).

Could you submit a pull request?

**Comment by kotfic** [comment]
+1
