### ISSUE TITLE
Ability to show/hide a standart command line

### ISSUE THREAD

**Issue by discort** [inducer/pudb#215]
At the moment there no ability to hide a command line panel which takes the considerable part of the screen.
Some people, for instance, me, are not using the bottom command line because it too small (resizing is not a deal, it covers code panel).
I propose to add hotkeys which hide/show command line panel.

cc @inducer  @asmeurer

**Comment by inducer** [comment]
Submit a patch, I might consider it. I think it might do better as a preference (rather than a hotkey), since it's not likely something you switch often.

**Comment by asmeurer** [comment]
You can press `_` to shrink the command line to its smallest size (use `+` and `-` to grow and shrink it).

**Comment by discort** [comment]
Yes, but:
a) the command line doesn't disappear completely;
b) after restarting a debugger I should do it again

**Comment by asmeurer** [comment]
We should definitely be saving the size of the command line.

**Comment by qhuy4119** [comment]
PuDB now saves the height of the internal command line.

**Comment by inducer** [comment]
Auto-hide of the built-in shell was also implemented recently.
