### ISSUE TITLE
Mention pytest-pudb plugin at pytest README section

### ISSUE THREAD

**Issue by wronglink** [inducer/pudb#226]
Hi there.

I'm author of `pytest` plugin [pytest-pudb](https://github.com/wronglink/pytest-pudb) that adds `pudb` debugger support the same way as it done for `pdb`. It can be used as cli argument `py.test --pudb` (note `--pudb` instead of `--pdb`) to run debugger on test fail. It also supports breakpoints via `set_trace` function. Plugin will automatically disable output capture for that case (no `-s` required).

I think it's little bit more handy then custom pytest debugger class support (via `--pdbcls` argument).

Would you like to mention pytest-pudb in the pytest README section?

**Comment by inducer** [comment]
Done, thanks for the pointer.

**Comment by asmeurer** [comment]
@wronglink @inducer how do you feel about just including this in PuDB? The --pdbcls method is impossible to remember, and the code seems simple enough (I'm unclear, though, exactly what you are doing with pudb.b. Should that be upstreamed?)

**Comment by inducer** [comment]
I wouldn't be opposed.

**Comment by wronglink** [comment]
@asmeurer I had some troubles with `pudb.b` frames depth, so I've reimplemented this feature in my package.

I'm not sure, if the `pytest` plugin should be included in `pudb` distribution (due to `pytest` package requirement and entry_points setup.py hacks, that pytest requires every plugin to provide). But if you think so, I can provide pull-request for moving `pytest-pudb` plugin into `pudb` codebase.

**Comment by asmeurer** [comment]
Yes, I had some issues figuring out how to make pudb.b work properly in Python 3. If you've figured out how to make it work this should definitely be fixed in PuDB itself.

Do we have to actually depend on pytest to install the plugin, or can we just install the entrypoint even if it isn't installed?

**Comment by wronglink** [comment]
> If you've figured out how to make it work this should definitely be fixed in PuDB itself.

Sorry, I guess I gave you the wrong explanation. As I can now remember the problem with `import pudb.b` satement was that I need to patch `set_trace` call inside the module (`pudb.b`) to switch  off output capturing. So when you put a `set_trace` breakpoint, you don't need to manually disable capturing at your tests. But as you import `b` module to patch `set_trace` inside it, it sets the breakpoint inside you plugin code :-) So I decided to emulate `import pudb.b` behaviour (breakpoint at import), and patch the full `pudb.b` module.
Finally I thing that pudb.b code is fine, that's why I haven't provided any PR here.

> Do we have to actually depend on pytest to install the plugin

I think the entrypoint is enough, and pytest could be an optional requirement. The problem is that pytest automatically enables all found plugins. An it could be a problem, if you want pudb to be installed, but dont need it as pytest plugin.

**Comment by asmeurer** [comment]
Does the plugin affect pytest in any way other than the --pudb flag? It doesn't seem to be a big deal if someone doesn't plan to use the plugin, they can just ignore that flag. But if it affects some other default debugging behavior in pytest that could be an issue I agree.

**Comment by asmeurer** [comment]
> Finally I thing that pudb.b code is fine, that's why I haven't provided any PR here.

Well dang. `pudb.b` actually is broken in Python 3 (it loads into the importlib module instead of the actual code) and I was hoping you found a fix.

**Comment by wronglink** [comment]
> pudb.b actually is broken in Python 3

Oh, didn't know that. I guess I can dig into it.

> Does the plugin affect pytest in any way other than the --pudb flag?

Yes. The same way as pytest pdb plugin does. It wraps `set_trace` and disables input and output streams capturing as it is called. It's done for 2 reasons:
1. It's not intuitive that you code fails with exception when it tries to get some user input (and you need to disable capturing manually).
2. When you disable capturing you can get lot of debug stdout information, you don't want to receive. And debugger plugin disables capturing only when it's needed.

The `--pudb` flag does another thing. It opens debugger when you get an exception in your code. It's quite handy because you don't need to set breakpoints manually.

I can change this behaviour to make plugin loadable depending on come config, but I'd like provide pretty similar behaviour that built-in pdb debugger plugin does.

**Comment by asmeurer** [comment]
But I mean, it won't affect pytest users who don't care about pudb, but happen to have it installed? Affecting pudb inside of pytest is fine. I think that making things just work is what we want. I would only be concerned if, for instance, it changed some pytest feature that normally uses pdb to use pudb. As far as I can tell it doesn't.

**Comment by wronglink** [comment]
Sounds reasonable. I think I'll try to provide PR moving `pytest-pudb` to `pudb` codebase.

**Comment by asmeurer** [comment]
@wronglink @inducer are you still interested in including pytest-pudb in pudb? I think just the fact that it makes `set_trace()` work even if you forget to use `pytest -s`makes it invaluable.

**Comment by inducer** [comment]
Yes, I'm all for that.
