### ISSUE TITLE
Drop into pudb from console connected to Notebook

### ISSUE THREAD

**Issue by AllanLRH** [inducer/pudb#229]
Is it possible to drop into Pudb from a console which is connected to a Jupyter notebook kernel? I mean connected like when running `jupyter-console --existing` which connects to the newest notebook kernel.

[I'm aware that I can't use Pudb from inside the notebook with web interface](https://github.com/inducer/pudb/issues/176), bur thought it might be possible this way.

My idea is to run the line which crashes from the connected Ipython (Jupyter console), just by copy-pasting it from the notebook to the terminal.

**Comment by inducer** [comment]
Pudb can do remote debugging (by opening a telnet port)--see the readme for more info. That might do what you need.

**Comment by sogaiu** [comment]
The suggested remote debugging method as documented here:

  https://documen.tician.de/pudb/starting.html#remote-debugging

worked nicely, thanks!

BTW, after exiting pudb, something seems to still be listening on the set up TCP port.  Is there a way to shut that down apart from killing the kernel process?

**Comment by inducer** [comment]
No, not currently. #289. Patches welcome.
