### ISSUE TITLE
tmux-256color terminal is not supported

### ISSUE THREAD

**Issue by lilydjwg** [inducer/pudb#231]
I have `TERM=tmux-256color` and my ncurses supports this. But the right panels of pudb have black spaces, no matter which "display driver" I choose.

Almost all other local terminal program I use (htop, vim, mutt) doesn't have problems with this setting.

![a](https://cloud.githubusercontent.com/assets/440661/24538275/cc762f1a-161a-11e7-853c-1bcdba2a5144.png)

**Comment by asmeurer** [comment]
I suspect this is an upstream urwid issue, but it would need to be investigated to be sure.

**Comment by inducer** [comment]
I use pudb in a 256-color tmux all the time, with no issue.

**Comment by klausmcm** [comment]
In case it still matters, I had the same problem. I use lxterminal in Debian.

I added this in .bashrc
    export TERM="screen-256color"

and now pudb shows colors properly.
