### ISSUE TITLE
Allow starting without pause

### ISSUE THREAD

**Issue by cool-RR** [inducer/pudb#234]
I want to make PuDB available in my script, but when I do `pudb.set_trace()`, I don't want it to stop there. I want it to stop only on breakpoints that I've already set (Saved in that config file.)

I'm not seeing a way to do that with PuDB, if there is maybe it should be in the readme.

**Comment by asmeurer** [comment]
I don't think there's a way. This is something I've often wanted before too. I would have expected `set_interrupt_handler()` to do it, but it doesn't. It shouldn't be hard to add. Should it be a separate function, or a flag to set_trace()? Do other debuggers like pdb or pdbpp implement this? 

Also, note that you can press `b` on a `set_trace()` call to disable it (for that run only, though).

**Comment by asmeurer** [comment]
PR at https://github.com/inducer/pudb/pull/235
