### ISSUE TITLE
Source code not found should recommend adding lines to linecache

### ISSUE THREAD

**Issue by asmeurer** [inducer/pudb#238]
If the source code is not found, it says 

```
If this is generated code and you would like the source code to show up here,
simply set the attribute _MODULE_SOURCE_CODE in the module in which this function
was compiled to a string containing the code.
```

I think it should also recommend adding the lines to `linecache`, which is doable even if you don't control the module, and will add support for other things as well (like the `traceback` module and `inspect.getsource`).

**Comment by inducer** [comment]
That's a good idea. PR?
