### ISSUE TITLE
Real documentation

### ISSUE THREAD

**Issue by asmeurer** [inducer/pudb#239]
The README is starting to reach the limits of what should go in a README, and I think it would be useful to have some real documentation (with lots of screenshots).  This would especially help since a lot of features are hard to discover, and many people may not realize that they exist (e.g., the fancy things you can do in the variables list). 

There's supposed to be some docs at https://wiki.tiker.net/PuDB, but that page is not working for me.

**Comment by inducer** [comment]
Yes, I'm totally supportive of that. RTD would probably be the right spot. We could start by just creating sections and splitting up the existing README...

> There's supposed to be some docs at https://wiki.tiker.net/PuDB, but that page is not working for me.

Huh, weird.

The rest of my wiki seems to be OK, but that page is down somehow. Not sure what happened there.

**Comment by asmeurer** [comment]
I figured you would want it on https://documen.tician.de/. I don't really care how it's hosted (GitHub pages is a third option).

**Comment by inducer** [comment]
Sure, documen.tician.de is easiest for me.

**Comment by jeffwidman** [comment]
One thing I really like about RTD is being able to flip through docs for different releases / master.

Does https://documen.tician.de/ support that?

**Comment by inducer** [comment]
No.
