### ISSUE TITLE
pudb 2017.1.1 gives file failed to compile

### ISSUE THREAD

**Issue by GreggJensen** [inducer/pudb#244]
I just updated to pub 2017.1.1 and when run with a script that worked just fine with the previous version now shows a pop up when I start pudb and set a breakpoint with the message:

The breakpoint you just set may be invalid, for the following reason:
File failed to compile.

I get this on all of my python scripts now, even the ones that are only a few lines.  I am running python 2.7 if that matters.  Any thoughts?  Maybe I missed something in the update that I was supposed to do also?

**Comment by asmeurer** [comment]
I can't reproduce, but it must be related to https://github.com/inducer/pudb/pull/228 somehow.

**Comment by asmeurer** [comment]
(By the way @inducer I think you didn't push the tag changes up to master)

**Comment by asmeurer** [comment]
Oh nevermind!

I thought 2017.1.1 was a recent release, but a release hasn't been done yet! So I expect #228 actually fixes this issue for you, once a new one is done.

**Comment by inducer** [comment]
Try 2017.1.2, just released.

**Comment by GreggJensen** [comment]
Yes, that did fix my issue!  Thanks.

**Comment by inducer** [comment]
Thanks for reporting back!
