### ISSUE TITLE
Add tags (topics) to github repo

### ISSUE THREAD

**Issue by wronglink** [inducer/pudb#251]
Github allows repo to add tags. It ease [the search](https://github.com/search?q=topic%3Adebugger&type=Repositories) and adds some metadata about repo:
![image](https://cloud.githubusercontent.com/assets/668115/25037168/f79ed768-2110-11e7-96db-e0254b769c17.png)

I think pudb repo should also have it's own tag list.

**Comment by inducer** [comment]
Added some.

**Comment by inducer** [comment]
Thanks for the suggestion.
