### ISSUE TITLE
Broken Github link in the docs page?

### ISSUE THREAD

**Issue by jcrben** [inducer/pudb#253]
Noticed that Github link in the left navigation at https://documen.tician.de/pudb/ goes to https://github.com/pyopencl/pudb.

Tried looking at the docs code https://github.com/inducer/pudb/tree/master/doc to make a PR but I couldn't seem to find it.

**Comment by inducer** [comment]
Thanks for the report! Should be fixed now.

**Comment by asmeurer** [comment]
Should we replace the homepage for PuDB on the top of the GitHub page with https://documen.tician.de/pudb/

**Comment by inducer** [comment]
Done.
