### ISSUE TITLE
Previus command is painted with delay when running under Docker

### ISSUE THREAD

**Issue by cdman** [inducer/pudb#274]
Because you respond so promptly, I reward you with more issues :). This one might not be an easy one to track down (and it might not even be related to PuDB but perhaps to urwid): when I run PuDB inside a Docker container (both the host and guest are Ubuntu 17.04) and I go to the Command line (Ctrl+X) and press Ctrl+P to get the previous command, the previous command is not painted until I move the focus away. This does not happen when running PuDB outside of Docker.

I know that this sounds confusing so I made a little video: https://asciinema.org/a/Lcx5SFyzqgvtJRYHIUfdIYTS1

What you're seeing:

- I'm starting the tests which are being run inside of a docker container
- I switch to the command line (Ctrl+X) and evaluate `self`
- Now I press Ctrl+P and expect to see `self` again
- But actually I don't see `self` until I press the right arrow to focus on the "<Clear>" button

I now just instinctively do right-arrow + left-arrow but perhaps there is a fix for this?

**Comment by inducer** [comment]
Not sure. I think we're interfacing with Urwid correctly, but you could
try to throw

```
self.cmdline_edit._invalidate()
```

into `cmdline_history_browse` to see if that serves as a workaround. If
it does, toss a PR referencing this bug in a comment in the code (so we
know why that `_invalidate` is there).

**Comment by cdman** [comment]
@inducer - I added `self.cmdline_edit._invalidate()` as the last line of `cmdline_history_browse` (ie. https://github.com/inducer/pudb/blob/676ee9d2fc0445ba492189431fb09631e1f65f9d/pudb/debugger.py#L1577), however it doesn't seems to have helped (I see no change in behavior).

Also, I seem to recall that this happens in a couple of places while running PuDB inside of Docker, the command line is just the most frequent one I use.

Also, perhaps it's relevant: the Dockerfile for this particular docker image contains the following lines:

```
# prevents the "dumb terminal when using docker exec" problem
RUN echo "export TERM=xterm" >> /root/.bashrc
```

**Comment by asmeurer** [comment]
Does the display driver setting (Ctrl-P, all the way at the bottom) affect this?

**Comment by cdman** [comment]
@asmeurer - no, doesn't seem to (and I restarted PuDB after changing the values between auto / raw / ncurses). Also, this seems larger than just the command line interface. For example the preferences window also doesn't paint until I do a right arrow. Like: `Ctrl+P` - nothing. After pressing the right arrow the preferences window is shown (and I'm focused on the OK button).

**Comment by cdman** [comment]
Some steps to reproduce it on any machine (hopefully):

- Start an Ubuntu 17.04 docker container: `docker run --rm -ti ubuntu:17.04` (this is an ephemeral container which will be removed after you exit it, just to conserve space)
- Install Python 3.5: `apt-get update && apt-get install python3 python3-venv`
- Create a virtualenv and install PuDB into it:
```
pyvenv pudb-debug
source pudb-debug/bin/activate
pip install pudb
```
- Create a test file: `echo 'print("Hello world!")' > test.py`
- Debug the file: `python -m pudb test.py`

Notice the issue reproducing (both with the command line and the preferences window). Also, setting the `TERM` variable to different values (or even unsetting it) doesn't seem to have any effect.

**Comment by cdman** [comment]
FYI, I also tried some of the urwid examples (https://urwid.readthedocs.io/en/latest/tutorial/), but I couldn't reproduce the issue with them.

**Comment by ges7** [comment]
This is because docker listens to catch the sequence Ctrl-P + Ctrl-Q to detach the terminal from docker. When the first Ctrl-P is hit, docker holds it and listens for the next character typed, if it's not Ctrl-Q, then it will forward *all typed keys* to the process running inside of it. Meaning, if you type Ctrl-P twice, it will hold the first one and then send both Ctrl-Ps to pudb, effectively going to the n-2 command in the history. To go to the last command when running pudb inside Docker I usually just do Ctrl-P + left arrow.

**Comment by cdman** [comment]
@ges7 - thank you for solving this issue! I didn't even know Docker had that feature :-)

So, the work around is to specify a different detach key sequence either on the command line or in the settings file (`~/.docker/config.json`). Something like:

`docker run --detach-keys 'ctrl-q,q' --rm -ti ubuntu:17.04`

See [the docker docs](https://docs.docker.com/engine/reference/commandline/cli/) for more details.
