### ISSUE TITLE
Adding break point like pdb

### ISSUE THREAD

**Issue by amosbird** [inducer/pudb#275]
Hi, how can I add breakpoints like this `b /home/amos/softwares/qutebrowser/qutebrowser/mainwindow/mainwindow.py:81` in pudb?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

**Comment by amosbird** [comment]
@inducer I'm sorry but it seems I cannot get any mails from the mailing list. This question troubles me for days and I wonder if you could give me some help. Thanks!

**Comment by inducer** [comment]
> @inducer I'm sorry but it seems I cannot get any mails from the mailing list. This question troubles me for days and I wonder if you could give me some help. Thanks!

Check your spam folder maybe.

**Comment by amosbird** [comment]
I did, and there isn't any related email.

**Comment by jeffwidman** [comment]
Hit up StackOverflow with questions than.

**Comment by asmeurer** [comment]
Not sure why no one wants to answer @amosbird but here's the answer:

Saved breakpoints can be added to `~/.config/pudb/saved-breakpoints-3.5` (replace 3.5 with your Python version), using the same format you describe (one per line). The actual path may differ depending on your platform (I think it uses xdg logic).

**Comment by amosbird** [comment]
Thanks @asmeurer
