### ISSUE TITLE
Enable Remote Debugging

### ISSUE THREAD

**Issue by aventurella** [inducer/pudb#28]
Per Issue:
http://lists.tiker.net/pipermail/pudb/2010-December/000000.html

I would be great to have remote debugging enabled to facilitate web application debugging. Where the debugger is initialized in the application and then pudb is able to attach to the process.

**Comment by gasull** [comment]
Why is this still open if rudimentary [remote debugging is already supported](https://documen.tician.de/pudb/starting.html#remote-debugging)?

**Comment by inducer** [comment]
Thanks for noticing this! I think a fair answer is that this should be closed, and new, more focused issues be opened with ideas for improvement of the current remote debugging code.
