### ISSUE TITLE
Pudb not being drawn at full width of the shell

### ISSUE THREAD

**Issue by mrvkino** [inducer/pudb#284]
Hi,

I am running pudb 2017.1.4 on macosx High Sierra. When I run pudb from my code (pudb.set_trace()) it draws the pudb interface on the left 1/4 of my shell.

I was able to replicate the behaviour with and without all my config on fish (aka bare fish shell). I tried it on iTerm and Terminal.

If I run the pudb3 <my script> command, the gui is fine.

pudb config:
```
[pudb]
breakpoints_weight = 1
current_stack_frame = top
custom_shell = 
custom_stringifier = 
custom_theme = 
display = auto
line_numbers = True
prompt_on_quit = True
seen_welcome = e033
shell = internal
sidebar_width = 1
stack_weight = 1
stringifier = type
theme = solarized
variables_weight = 1
wrap_variables = False
```

pip3.4 package:
```
autopep8 (1.3.3)
flake8 (3.5.0)
mccabe (0.6.1)
pip (9.0.1)
ptvsd (3.2.1)
pudb (2017.1.4)
pycodestyle (2.3.1)
pydocstyle (2.1.1)
pyflakes (1.6.0)
Pygments (2.2.0)
setuptools (38.2.1)
six (1.11.0)
snowballstemmer (1.2.1)
urwid (1.3.1)
wheel (0.30.0)
yapf (0.20.0)
```

pudb.set_trace()
![pudb](https://user-images.githubusercontent.com/279511/33355409-617d4df4-d485-11e7-8a98-e2d3fe7c99cf.jpeg)

**Comment by inducer** [comment]
Looks like Urwid is mis-detecting the terminal width. Maybe something in your app reset `$COLUMNS`?

**Comment by mrvkino** [comment]
It seems to be the makefile that calls the script that cause the issue. I am able to have the pudb gui appear correctly if I call the script directly/

**Comment by tommyjcarpenter** [comment]
I still have this same issue 5+ years later

**Comment by mcstafford-git** [comment]
For some reason this started happening to me today after using pudb without a problem for years.

**Comment by asmeurer** [comment]
What's the output of

```
from urwid.raw_display import Screen
print(Screen().get_cols_rows())
```

That should be the number of rows and columns in your terminal. If it doesn't match, there is something in the logic of that urwid function that is messing up.
