### ISSUE TITLE
Cannot use pudb for multiprocessing

### ISSUE THREAD

**Issue by xuananh-viosoft** [inducer/pudb#286]
I am trying to use pudb to debug with multiprocessig, but I encounter error as below:
Code:

```
import pudb
import multiprocessing
import time

def worker():
    i = 0
    while i < 10:
        pudb.set_trace()
        i = i + 1
        time.sleep(1)
    
if __name__ == '__main__':
    p1 = multiprocessing.Process(target=worker)
    p1.start()
```

Error:

> Process Process-1:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "pudb_sample.py", line 9, in worker
>     i = i + 1
>   File "pudb_sample.py", line 9, in worker
>     i = i + 1
>   File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
>     return self.dispatch_line(frame)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 160, in dispatch_line
>     self.user_line(frame)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 381, in user_line
>     self.interaction(frame)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 349, in interaction
>     show_exc_dialog=show_exc_dialog)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2089, in call_with_ui
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2330, in interaction
>     self.event_loop()
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2274, in event_loop
>     % VERSION)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 1927, in message
>     [("OK", True)], title=title, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2089, in call_with_ui
>     return f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2008, in dialog
>     return self.event_loop(w)[0]
>   File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2290, in event_loop
>     keys = self.screen.get_input()
>   File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 325, in get_input
>     keys, raw = self.parse_input(None, None, self.get_available_raw_input())
>   File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 427, in get_available_raw_input
>     codes = self._get_gpm_codes() + self._get_keyboard_codes()
>   File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 501, in _get_keyboard_codes
>     code = self._getch_nodelay()
>   File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 635, in _getch_nodelay
>     return self._getch(0)
>   File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 545, in _getch
>     return ord(os.read(self._term_input_file.fileno(), 1))
> TypeError: ord() expected a character, but string of length 0 found

Does anyone know about this problem?

**Comment by inducer** [comment]
Not a bug. `multiprocessing` workers do not have anything attached to stdin, so no interactive debuggers. Try [remote debugging](https://documen.tician.de/pudb/starting.html#remote-debugging).

**Comment by Fangyh09** [comment]
Still failed using remote debugging.
```bash
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 114, in train_rpn
    cfg.TRAIN.HAS_RPN = True
  File "./tools/train_faster_rcnn_alt_opt.py", line 114, in train_rpn
    cfg.TRAIN.HAS_RPN = True
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb-2017.1.4-py2.7.egg/pudb/debugger.py", line 187, in dispatch_line
    self.user_line(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb-2017.1.4-py2.7.egg/pudb/debugger.py", line 408, in user_line
    self.interaction(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb-2017.1.4-py2.7.egg/pudb/debugger.py", line 376, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/usr/local/lib/python2.7/dist-packages/pudb-2017.1.4-py2.7.egg/pudb/debugger.py", line 2116, in call_with_ui
    self.show()
  File "/usr/local/lib/python2.7/dist-packages/pudb-2017.1.4-py2.7.egg/pudb/debugger.py", line 2107, in show
    self.screen.start()
  File "/usr/local/lib/python2.7/dist-packages/urwid/display_common.py", line 742, in start
    self._start(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 203, in _start
    self.write(escape.SWITCH_TO_ALTERNATE_BUFFER)
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 268, in write
    self._term_output_file.write(data)
  File "/usr/lib/python2.7/codecs.py", line 828, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 370, in write
    self.stream.write(data)
  File "/usr/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
AttributeError: 'NoneType' object has no attribute 'sendall'
```

**Comment by jstriebel** [comment]
In #402 I introduced `pudb.forked.set_trace` exactly for the use-case of multiprocessing, fixing this:
https://documen.tician.de/pudb/starting.html#using-the-debugger-after-forking

**Comment by inducer** [comment]
Thanks @jstriebel. Closing this. Please comment if you believe that this hasn't been addressed (on the master branch).
