### ISSUE TITLE
Remote debugger leaves its socket open

### ISSUE THREAD

**Issue by inducer** [inducer/pudb#289]

**Comment by sogaiu** [comment]
Current work-around here is to do:

```python
pudb.remote.debugger().do_quit(1)
```

after quitting a debugging session with pudb.

This made it possible to successfully start a new session and connect to it -- though depending on the situation may be on a higher port number.

**Comment by inducer** [comment]
Thanks! I'd be happy to take a patch that makes this "just work".

**Comment by Munk801** [comment]
This is great.  Glad to know I can at least close this as my terminal was getting blown if I just quit.

**Comment by inducer** [comment]
#450 should have fixed this. Please comment if not.

**Comment by sogaiu** [comment]
@inducer I tried with b36b10e8905971c700ddb6b41bf6102ea0a310c4 and it seems to be working :+1:
