### ISSUE TITLE
How to make the inner shell larger?

### ISSUE THREAD

**Issue by Fangyh09** [inducer/pudb#290]
I have tried "+" to grow the shell, but failed.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by Fangyh09** [comment]
@inducer Thanks.

**Comment by Fangyh09** [comment]
@inducer 
I made it by changing weight in pudb/debugger.py line 697
```python
self.lhs_col = urwid.Pile([
    ("weight", 5, self.source_attr),
    ("weight", 1, self.cmdline_sigwrap),
    ])
```

**Comment by Fangyh09** [comment]
@asmeurer You can modify  pudb/debugger.py line 697
```python
```
