### ISSUE TITLE
Cannot step into a function within lambda.

### ISSUE THREAD

**Issue by Fangyh09** [inducer/pudb#291]
I add a breakpoint on this line, but can not step into function pascal_voc.
```python
__sets[name] = (lambda split=split, year=year: pascal_voc(split, year))
```
For reproduce,
```python
#/bin/python
a=[1,2]
b=[3,4]

def add(a,b):
    c=a+b
    return c

out=(lambda x=a[0], y=b[0]: add(x,y))
print(out)
```

**Comment by asmeurer** [comment]
The lambda isn't executed. I think you are perhaps confusing LISP syntax and Python syntax. `(lambda x: f())` is the same as just `lambda x: f()`. The extra parentheses are redundant. If you want to call the lambda you have to call it like function, with parentheses at the end, like `out()`.

I tested it and stepping into a function called from a lambda works fine (although you have to press `s` twice for some reason).

**Comment by Fangyh09** [comment]
@asmeurer 
I tested on this code
```python
```

**Comment by emj** [comment]
@Fangyh09 you need something like:` print(out()) ` to execute a lambda, until you execute it all you have is an lambda and that on it self will not execute, and code that is not executed is not  steped into.
