### ISSUE TITLE
variables that start with underscores or dots not shown

### ISSUE THREAD

**Issue by asmeurer** [inducer/pudb#292]
From this line https://github.com/inducer/pudb/blob/3f627ce0f7370ab80bc2496cb3d2364686f10efe/pudb/var_view.py#L556 variables that start with `_` or `.` in the current namespace aren't show. This is separate from the method name filtering. For instance

```
a = 1
_b = 2
c = 3
```

if you run pudb on this script, only `a` and `b` are shown. 

Why is this filter here? It seems to me it should only filter things that start and end with `__`, to get rid of `__builtins__`, `__file__`, and so on. And why is the filter for `.` there? A variable name can only start with `.` if something manually put it in `globals()`.

**Comment by inducer** [comment]
> Why is this filter here? It seems to me it should only filter things that start and end with __, to get rid of __builtins__, __file__, and so on.

I agree. I think I was just being sloppy. Feel free to fix.

> And why is the filter for . there?

I honestly don't remember. it doesn't make much sense to me any more, either.

**Comment by asmeurer** [comment]
I checked the commit history. It goes back to 07ab4107, which doesn't mention anything about it.
