### ISSUE TITLE
Run till current line 

### ISSUE THREAD

**Issue by Alok** [inducer/pudb#295]
"run until current line" breaks on multiline expressions such as the trivial program:

```python
a = 1

a = \
    2

print(a)
```

Putting the cursor on the line `a = \` and hitting `t` will give an error, even though it's part of a larger expression.

**Comment by inducer** [comment]
It's performing as designed. I agree that what you ask for would be nice to have, but Python's line number information is not precise enough to be able to recognize where a statement begins and ends. All code for each statement is attributed to the statement's last line. Also, any heuristics you might come up with (continue to the next line on which there's code, e.g.) tend to have subtle correctness issues.
