### ISSUE TITLE
HELP! the scale of codes and stack/breakpoints/variables is broken

### ISSUE THREAD

**Issue by yd-yin** [inducer/pudb#308]
![image](https://user-images.githubusercontent.com/37136395/43845496-b5d55b9e-9b5e-11e8-9157-94d325fb2ef7.png)
that's not look good
I just want to debug quietly
HELP!

I'v tried uninstall and install again. Is there any reset button?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

`rm -Rf ~/.config/pudb`

Also, the help screen (? key) has hints on how to adjust pane sizes.

**Comment by yd-yin** [comment]
Thanks a lot! It's really kind of you.
Sorry for coming to a wrong room for solving problems:)
