### ISSUE TITLE
Attach to an existing running process

### ISSUE THREAD

**Issue by stenyak** [inducer/pudb#31]
It would be desirable to be able to attach to an already running python process, breaking its execution.
Similar to gdb -p <PID>

**Comment by inducer** [comment]
Thanks for the pointer. That looks like an interesting project.

**Comment by kmaork** [comment]
Would be glad to assist with adding this feature. Note that there's a new WIP version (https://github.com/kmaork/madbg/pull/44) with many important improvements and a redesign, also adding support for multithreaded debugging.
