### ISSUE TITLE
Changing the keyboard shortcut to invoke pudb

### ISSUE THREAD

**Issue by jaepetto** [inducer/pudb#312]
Would it be possible to change he keyboard shortcut to invoke pudb?
The documentation states that we should hit `Ctrl+c`.
The problem is that signal is also used by Django runserver to kill the web server.
Therefore, when I hit `Ctrl+c`, I get in the debugger, then (by pressing c), the web server stops.

**Comment by inducer** [comment]
I think the issue is more that both pieces of software listen for SIGINT, and there isn't another signal like it, much less one whose keyboard shortcut we could control (if I understand correctly.)

**Comment by jaepetto** [comment]
Yes. You did get it correctly... I was afraid you would say that...

**Comment by asmeurer** [comment]
We could add a handler for another signal and you could activate it manually in another terminal with `kill`.

**Comment by asmeurer** [comment]
Actually this is already supported. See the docstring of `set_interrupt_handler`.
