### ISSUE TITLE
Support debugging from a separate terminal (without using current stdin/stdout).

### ISSUE THREAD

**Issue by swarmer** [inducer/pudb#313]
So using pudb in multithreaded programs is quite painful because secondary threads tend to keep writing shit to stdout and it messes up debugging. What we want then is to access pudb in a separate terminal without involving normal stdin/stdout.

I've experimented a bit with this and thankfully pudb's Debugger has stdin/stdout arguments so this was pretty easy to do. Seems to work ok, except that ipython insists on using the original tty, so I had to pick the internal repl (I haven't looked into this, may be easy to fix).

I want to make my hack more integrated/official/documented. What is involved:  
- Opening a separate terminal in really just a shell one-liner (I used tmux, although this is kind of optional). So It would probably make sense to just describe it in the documentation.
- We need to open tty that we just attached to above and pass it to pudb. I'd add an argument[s?] to `set_trace` and mention this in the doc.

I'll do this if I'll get the go-ahead from maintainers, or if you have any other ideas on how to do this better, I'd love to hear them.

**Comment by inducer** [comment]
I'd be happy to have something like this. If you could somehow automate the process of spawning a tty (or tmux pane) with tmux or another terminal connected in a somewhat convenient manner (`pu.dterm`?), I think this would become a popular feature quite quickly.

**Comment by swarmer** [comment]
I don't think `pu.dterm` can work because we need to create a separate terminal. Opening a new terminal in a cross-platform way sounds like a PITA and even then, which size do we make it? (autoresizing didn't work in my testing, don't know how hard to fix this).

What we can do is: if an env variable, say `PUDB_TTY`, is defined, then `pu.db` instead of using the normal terminal, will use whatever is in this variable. So you would need to open a terminal beforehand and point pudb to that.

Anyway, I'm hoping to make something runnable on this weekend to get feedback.

**Comment by inducer** [comment]
In order to receive `SIGWINCH`, the new terminal would need to become the "controlling terminal" of the process. [Dive in](https://blog.nelhage.com/2011/02/changing-ctty/) if you're curious.
