### ISSUE TITLE
Using pudb in a separate terminal with Django runserver

### ISSUE THREAD

**Issue by jaepetto** [inducer/pudb#319]
**Description**
pudb does not display the GUI into a separate terminal

**Steps to reproduce**
* Open one terminal (t1) and get the id of the tty (`tty`). Here, the result is `/dev/pts/5`
* Open another terminal (t2)
* update the django code by adding
  ```python
  import pudb; pu.db
  ```
* launch django development server
  ```shell
  PUDB_TTY=/dev/pts/5 sudo runserver ...
  ```

**Current behaviour**
pudb opens on the second terminal (t2)

**Expected behaviour**
the pudb gui should display on the first terminal

**Comment by inducer** [comment]
That would require transplanting an existing process onto a different terminal. I'm not sure that's even possible.
