### ISSUE TITLE
How can I use pudb in a HPC (cluster)?

### ISSUE THREAD

**Issue by curry111** [inducer/pudb#322]
Hi :sweat_smile: :sweat_smile:  thank you so much for that amazing debugger. my problem is that pudb does not work normally on the HPC. I use SLURM for job scheduling on the cluster. 
when I request an interactive job on the compute nodes I run 
`salloc --partition=cpu --nodes=1  --time=01:00:00   
`
`
srun python aa.py
` 

in the `aa.py` file, I start by `from pudb import set_trace; set_trace()`.
the debugger shows like this
![11](https://user-images.githubusercontent.com/25343445/48963165-d0f9d680-ef95-11e8-92e2-8d11f727cad6.png)
It does not move when I hit "n", even If i hit "n" multiple times. it only moves when I hit "enter"
![33](https://user-images.githubusercontent.com/25343445/48963174-f4bd1c80-ef95-11e8-8fe6-0cb25d16f773.png)
I also can't type in the command line by hitting "CTRL+X"
![444](https://user-images.githubusercontent.com/25343445/48963184-15857200-ef96-11e8-81b2-4028213d3d20.png)
Why is that happening and how can i fix it? :sweat_smile: 
PS: the debugger works fine on the login node(not the compute nodes)

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
