### ISSUE TITLE
Pickle can't get user-defined class definition

### ISSUE THREAD

**Issue by AleGiuva** [inducer/pudb#331]
The pickle module is used to serialize and de-serialize a Python object structure, also user-defined objects.
Under pudb if pickle tries to load an user-defined class definition, an error is raised:

AttributeError: Can't get attribute 'Foo' on <module 'pudb.run' from '/usr/local/lib/python3.7/site-packages/pudb/run.py'

This happens with PuDB 2018.1 ran on Python 3.7.2 under Debian 9.8, but as long as i remember this always happened since Python 2.

After some investigation, I found that the problem is pudb don't clear his `__main__` and replace it with the script to debug.

pickle loading works good under the Python debugger pdb (not pudb), so I've compared the codes and found that inside pudb.debugger on line 437 a new globals_ dict is built. pdb instead just clean it and add some special variables. So I've tried to copy some pdb lines to let pudb behave like the first, and the issue was solved:

delete
```
437: globals_ = {"__name__": "__main__", "__file__": filename}
438: locals_ = globals_
```
replace with
```
import __main__
__main__.__dict__.clear()
__main__.__dict__.update({"__name__"    : "__main__",
                          "__file__"    : filename,
                          "__builtins__": __builtins__,
                         })
```
delete
```
457: self.run(statement, globals=globals_, locals=locals_)
```
replace with
```
self.run(statement)
```

I can't tell if this broke something, I've not inspected further and I don't know thoroughly how import works, but I hope this could help.
This is my first github issue so please be gentle :) .

**Comment by inducer** [comment]
I take it you mean a class that's defined in a script being debugged? Could you supply an example of code that breaks when debugged and instructions on how to trigger the behavior?

**Comment by AleGiuva** [comment]
Yes, in a script being debugged. pickle needs the user-defined class being in the `__main__` namespace or would raise an `AttributeError: Can't pickle local object`

with a simple user-defined class
```
class Foo:
    def __init__( self ):
        self.bar = 1
```
`pickle.dump({ "foo": Foo() }, open( "pickle", "wb" ))` raises an error with this traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pudb/__init__.py", line 119, in runscript
    dbg._runscript(mainpyfile)
  File "/usr/local/lib/python3.7/site-packages/pudb/debugger.py", line 457, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/local/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "pudb-pickle.py", line 11, in <module>
    pickle.dump({ "foo": Foo() }, open( "pickle", "wb" ))
_pickle.PicklingError: Can't pickle <class '__main__.Foo'>: attribute lookup Foo on __main__ failed
```
saving without pudb works good, but
`pickle.load( open( "pickle", "rb" ))` under pudb has this traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pudb/__init__.py", line 119, in runscript
    dbg._runscript(mainpyfile)
  File "/usr/local/lib/python3.7/site-packages/pudb/debugger.py", line 457, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/local/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "pudb-pickle.py", line 14, in <module>
    pickle.load( open( "pickle", "rb" ))
AttributeError: Can't get attribute 'Foo' on <module 'pudb.run' from '/usr/local/lib/python3.7/site-packages/pudb/run.py'>
```

**Comment by inducer** [comment]
Reproduced, and I can confirm that your suggested changes address the issue and appear to make sense.

https://gitlab.tiker.net/inducer/pudb/merge_requests/7
