### ISSUE TITLE
Feature Request: pudb -m module.name just like python -m module.name

### ISSUE THREAD

**Issue by w-hc** [inducer/pudb#341]
Hi, I wonder if it would be possible to invoke a module directly from the command line with pudb.
```bash
pudb -m module1.submodule2
```

**Comment by inducer** [comment]
Sure, I'd be happy to consider a patch/PR.

**Comment by eliasdorneles** [comment]
Will be closed by: https://github.com/inducer/pudb/pull/390

**Comment by frou** [comment]
This issue should be closed I think, since the feature was added a while ago
