### ISSUE TITLE
Drop Python 2.6 support

### ISSUE THREAD

**Issue by inducer** [inducer/pudb#343]
It has finally happened: I got sick of supporting Python 2.6, and I feel the costs outweigh the benefits. (Hey, you can always install an old version!)

@asmeurer, any objections?

[This](https://gitlab.tiker.net/inducer/pudb/merge_requests/9) is where that change currently hangs out.

**Comment by inducer** [comment]
@asmeurer I seem to recall you were pushing to drop 2.6 long ago, so I'll assume you're OK with the change.

**Comment by asmeurer** [comment]
Fine with me. I've stopped needing to care about 2.6 a long time ago.

What is the situation with GitLab?

**Comment by inducer** [comment]
> What is the situation with GitLab?

Not sure there is a situation. I maintain a private Gitlab instance where I do some of my development. (I quite like Gitlab. Especially the CI and WebIDE aspects are really well done. Discussions, suggestions, and reviews are also nicely implemented. I actually prefer it to Github in some respects, and it was a convenient thing to have before Github had free private repos.) But I don't have any plans to move the "official/public repo" away from Github soon, or ever.

**Comment by asmeurer** [comment]
OK, that was my main question, if there were plans to me. I personally find some aspects of GitLab annoying compared to GitHub, although I would mainly prefer to keep this repo around just so it isn't dependent on your own server being up.
