### ISSUE TITLE
Suggestion: jump to breakpoint

### ISSUE THREAD

**Issue by andrecianflone** [inducer/pudb#354]
It would be great to jump from one breakpoint to the next with a shortcut (without running code). Also, it would be really helpful if after focusing on the Breakpoints window one could simply hit a key like "l" to go to the breakpoint under the cursor. At the moment, if I want to go to a breakpoint location I have to press Ctrl-B, hit 'enter', hit the right arrow key, scroll to 'location' and hit enter again.

Thanks for pudb, great debugger!

**Comment by bulletmark** [comment]
I'm recently new to pudb but thought the same thing as you so submitted PR  #351 which was merged to master just 8 hours ago. Switch to the breakpoints list and press enter on each one as you scroll through them. Try it out.

**Comment by andrecianflone** [comment]
@bulletmark this is perfect. I just installed the latest on master branch, works great. Thanks!
