### ISSUE TITLE
Configurable Pane Arrangement

### ISSUE THREAD

**Issue by dissolved** [inducer/pudb#356]
Being able to grow and shrink the sidebar is nice, but it only allows me to grow a particular pane horizontally, not vertically. Furthermore, sometimes I want to hide entire panes. I'm often just interested in a code pane and a variable pane. I would love to have full control over what panes are visible and the size of each pane (including its height, not just its width).

**Comment by inducer** [comment]
Height control for the sidebar panels is available, see the help text. Visibility, not currently.

**Comment by bulletmark** [comment]
Actually, visibility does seem to be currently supported. You can manually set one or more of the `_weight` settings to 0 in the configuration file. The associated pane is then completely hidden.

**Comment by dissolved** [comment]
@inducer I actually had read the help text, and kept hitting the `/` key, not noticing it was just a separator for the `[` and `]` keys  🤦‍♂ 

@bulletmark Cool I'll check that out.

Closing the issue.
