### ISSUE TITLE
Is Numpy a requirement?

### ISSUE THREAD

**Issue by fdelacruz** [inducer/pudb#357]
Is Numpy needed in order to run pudb??
I get the following error when I don't have it installed.
> AttributeError: module 'numpy' has no attribute 'ndarray'
Not a huge issue, but it's not listed anywhere (AFAIK) as a requirement.
Thanks

**Comment by asmeurer** [comment]
Numpy is used if it is installed to show ndarrays nicer in the variables view but it isn’t required. It sounds like you have a broken numpy module. Do you maybe have a directory called “numpy” in your current directory?

**Comment by fdelacruz** [comment]
@asmeurer yes, it seems like I had a lingering numpy folder in my /usr/local/lib/python3.7/site-packages. Thanks.
