### ISSUE TITLE
pudb crashes in `import torch`

### ISSUE THREAD

**Issue by Paethon** [inducer/pudb#358]
When I try to debug a script using pytorch, pudb crashes with the following error on the line `import torch`.

    terminate called after throwing an instance of 'std::runtime_error'
        what():  expected ) but found 'ident' here:
    quantized::fake_quantize_per_tensor_affine_forward(Tensor X, float scale, int zero_point, int num_bits = 8, int quant_delay = 0, int iter = 0) -> Tensor
                                                                                                                ~~~ <--- HERE

    fish: “pudb3 eval.py --modelfile ./mod…” terminated by signal SIGABRT (Abort)

The script does work when not using `pudb` (It also works when I am debugging with `pdb`)

**Comment by inducer** [comment]
Can't reproduce. Using
```
Python 3.7.4 (default, Aug 21 2019, 16:01:23) 
[GCC 9.2.1 20190813] on linux
```
I made a virtualenv, ran `pip install torch` and ran `python -m pudb a.py` where `a.py` is:
```python
import torch
print("HI")
```
runs without a problem.
