### ISSUE TITLE
pudb kills ipython session on exit

### ISSUE THREAD

**Issue by jfmoulin** [inducer/pudb#364]
When working under ipython (ver), if a script raises an error and I do a post mortem
analysis it seems impossible to get back to my original ipython session.
This is pretty annoying in case the script is debugged after a computing intensive preparation step in the interactive shell. 

 steps to reproduce:

    under ipython 7.4.0: 

        - run a script that raises an exception
        - pudb.pm()
        - ! #to get a shell (ipython in my case)
        - hack hack...
        - ctrl D # to exit the shell and return to pudb
        - exit debugger or continue to next statement 
 		-> does not return to initial ipython session but quits alltogether

It seems this happens only if I invoke an ipy shell from the pudb. If I simply inspect code and exit everything works fine and I get back to my original shell session.

**Comment by asmeurer** [comment]
I guess when you exit the inner shell, it causes IPython to completely shut down. IPython unfortunately only ever has a single shell instance globally. 

Probably the simplest way to fix it would be to temporarily override `exit()` and `Ctrl-D` in the inner shell to just exit the shell without shutting it down.

**Comment by asmeurer** [comment]
Maybe we can catch SystemExit. I don't know if the cleanup happens before or after it is raised.

**Comment by jfmoulin** [comment]
Indeed, I had a look at  [IPy's doc](https://ipython.readthedocs.io/en/stable/interactive/reference.html#embedding-ipython) and it states:

> At present, embedding IPython cannot be done from inside IPython. Run the code samples below outside IPython.
so there are probably complications.
Maybe I should raise the issue at IPython's page...
