### ISSUE TITLE
Impossible to set breakpoint in Python 3.8

### ISSUE THREAD

**Issue by lega911** [inducer/pudb#366]
Python 3.8 + PuDB 2019.1  (but it works in python 3.6, and with pdb python 3.8)

When I try to set breakpoint I receive modal form "Possibly Invalid Breakpoint" (also "run to cursor" doesn't work).
So it's impossible set breakpoint after slash `\` (after 3rd line)
Source:
```python
def main():
    import pudb; pu.db
    conf = ''. \
        replace('', '')

    conf_tpl = ''  # <-- imposible to set breakpoint here

main()
```

**Comment by asmeurer** [comment]
Python 3.8 must have changed the way co_lnotab works (see pudb/lowlevel.py). I don't see anything in the 3.8 release notes about it.

**Comment by asmeurer** [comment]
It is mentioned in the full changelog. These seem relevant

https://bugs.python.org/issue38115
https://bugs.python.org/issue26107

**Comment by asmeurer** [comment]
https://github.com/python/cpython/blob/master/Objects/lnotab_notes.txt

I think we aren't handling the larger than 255 thing. Debugging the `generate_executable_lines_for_code` function your example, it generates line numbers of 259 and 262.

**Comment by asmeurer** [comment]
Here's a fix that uses the example code from that file https://github.com/inducer/pudb/pull/367. It fixes the example here, but I haven't tested it beyond that.

**Comment by endlisnis** [comment]
I noticed something similar in:
`def do(city, **kwargs):
    pass

do(1,
   running=None)
do(1)  <=== Cannot set breakpoint here
`
