### ISSUE TITLE
How to not quit pudb when executing to the end? 

### ISSUE THREAD

**Issue by c02y** [inducer/pudb#374]
When I'm debugging a python program, and I executed a lot commands in the `Command line` window, and after using `c` to executing to the end of the program, pudb will exit, I have to start pudb again, but the `Command line` window becomes empty, I have to type all the commands I have typed instead using `C-n/p`.

How to not quit pudb when executing the program to the end, I mean just start over the process from the beginning?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

You see a screen that looks like this:

![Bildschirmfoto von 2019-12-27 12-14-16](https://user-images.githubusercontent.com/352067/71515217-7589ce80-28a2-11ea-99c5-92d90fbef681.png)

and you press restart.
(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)

**Comment by c02y** [comment]
Thank you, I didn't enable "Prompt before quitting", now I get it, thanks.

**Comment by benjamin-kirkbride** [comment]
> I didn't enable "Prompt before quitting", now I get it, thanks.

How does one enable this? and more importantly, how does one disable it?

**Comment by inducer** [comment]
In the settings, press Ctrl-P.
