### ISSUE TITLE
screen flash at every debugger step

### ISSUE THREAD

**Issue by neeraj-j** [inducer/pudb#380]
HW: Raspberry pi3 B+
OS: Raspibian "Buster" Desktop 
xterm: xterm-256color

Everytime I do next step in debugger, I see flicker on screen. I am not using ssh. I saw some old posts on this issue. still not sure about the fix. Can someone help me with it. Apart from this issue, I find it great!!

**Comment by asmeurer** [comment]
Duplicate of https://github.com/inducer/pudb/issues/48. See the discussion there.
