### ISSUE TITLE
pudb_stringifier(obj) not called for int()

### ISSUE THREAD

**Issue by jlescher** [inducer/pudb#384]
I would like to be able to display ints as hexadecimal.
However it seems that pudb_stringifier(obj) is not called for int values.

Is there any reason why ?

**Comment by asmeurer** [comment]
I guess the original idea is that the stringifier is only needed for unsafe types. But it would probably be better to implement a default stringifier and have the custom one override it (the default one can be part of the API so that custom ones can fall back to it).

**Comment by inducer** [comment]
> But it would probably be better to implement a default stringifier and have the custom one override it (the default one can be part of the API so that custom ones can fall back to it).

I like this idea.

**Comment by mvanderkamp** [comment]
I agree this would be useful. The changes in #417 would make this easier since it simplifies the code to test for all the basic types at once, but this is generally independent of that changeset so there's no need to wait on it.

Possibilities that I see:
1. Always use `repr()` by default for the basic types, but allow custom stringifiers
2. Don't treat the basic types as distinct from other types.
3. Provide a config option for toggling between 1. and 2.

**Comment by inducer** [comment]
How about we simply move the check for the basic types into the default stringifier? (i.e. not "type", but "type-or-basic-value")

**Comment by asmeurer** [comment]
Isn't that what is already happening at https://github.com/inducer/pudb/blob/da44ac39d956cf0a73cfc3b5969f4b86f500a1c4/pudb/var_view.py#L289? The only thing I don't like about that is that the name "type" is misleading. IMO "type" should literally just be `type` and the current `type_stringifier` should be called something else.

**Comment by mvanderkamp** [comment]
Interesting, I think I like that idea. How about "default" for the existing one?

**Comment by inducer** [comment]
"default" is fine by me. Essentially, [this bit of code](https://github.com/inducer/pudb/blob/da44ac39d956cf0a73cfc3b5969f4b86f500a1c4/pudb/var_view.py#L376-L381) would simply have to go, to give more power to the stringifiers.

**Comment by asmeurer** [comment]
I like "safe" for a name. I think that's what we already call it in some places anyway. Although "default" is better for a keyboard shortcut (s is already taken for str).

**Comment by inducer** [comment]
#384 should be addressed via its number-anagram #438 by @mvanderkamp. :)
