### ISSUE TITLE
Support running as module (`pudb3 -m some_module`)

### ISSUE THREAD

**Issue by eliasdorneles** [inducer/pudb#389]
It would be nice if we could run `pudb3 -m some_module ....` similarly to how we can do with pdb (`python -m pdb -m some_module`).

This is useful when you want to debug some code not necessarily written by you, which you must run with `python -m module`.

**Comment by inducer** [comment]
I agree. I'd be happy to take a patch.

**Comment by eliasdorneles** [comment]
Closing this, now that #390 is merged :)
