### ISSUE TITLE
Yucky console error message when custom stringifier not found

### ISSUE THREAD

**Issue by endlisnis** [inducer/pudb#401]
Sometimes, when I'm using pudb to step through code and inspect variables, I will get this message popping up:

```
Error when importing custom stringifier:
Traceback (most recent call last):
  File "/home/rolf/.local/lib/python3.8/site-packages/pudb/var_view.py", line 315, in get_stringifier
    execfile(expanduser(iinfo.display_type), custom_stringifier_dict)
  File "/home/rolf/.local/lib/python3.8/site-packages/pudb/py3compat.py", line 13, in execfile
    exec(compile(open(fname).read(), fname, 'exec'), globs, locs or globs)
FileNotFoundError: [Errno 2] No such file or directory: ''
Hit enter:
```

I'm not using a customer stringifier that I'm aware of, and hitting enter just gets me into a loop of this error printing out.

I'm using python3.8 on Linux Mint, pudb version "2019.2".

**Comment by inducer** [comment]
Closed by #429.

**Comment by inducer** [comment]
(Thanks @mvanderkamp!)

**Comment by endlisnis** [comment]
Great.  When will this get pushed out to pip?  I'd like to give it a try.
