### ISSUE TITLE
Catch exceptions raised by safely_stringify_for_pudb

### ISSUE THREAD

**Issue by inducer** [inducer/pudb#406]
As @mvanderkamp remarks in https://github.com/inducer/pudb/pull/404#issuecomment-688479457:

We should catch exceptions raised in `safely_stringify_for_pudb` and show that an error occurred in the shown value.

**Comment by mvanderkamp** [comment]
Is this still an issue? I think #404 ultimately wound up resolving it.

**Comment by inducer** [comment]
Agree. Closing.
