### ISSUE TITLE
Starting pudb by specifying a module (not a script)

### ISSUE THREAD

**Issue by selitvin** [inducer/pudb#411]
Does pudb has an equivalent of `ipdb`'s `-m` switch? (the switch allows to launch a debugger by specifying a module and not a script). This feature would make it easier to integrate the debugger in some build-system configurations, like the one used in our organization.

**Comment by asmeurer** [comment]
This feature was just added https://github.com/inducer/pudb/pull/390. Although I don't know if a release has been done since then.
