### ISSUE TITLE
multiprocessing/spawn.py,  in get_preparation_data,  module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by sisrfeng** [inducer/pudb#415]
Would you mind telling me how to solve it? (There is no bug while runing with python instead of pudb)
![image](https://user-images.githubusercontent.com/53520949/103143353-5a6ccb80-474f-11eb-92bb-129d00becf61.png)

**Comment by inducer** [comment]
Without better instructions to reproduce the problem you are facing, we can't really help you.

**Comment by qhuy4119** [comment]
This error doesn't seem to be specifically pudb's fault . See here: https://stackoverflow.com/questions/45720153/python-multiprocessing-error-attributeerror-module-main-has-no-attribute
