### ISSUE TITLE
Setting environmental variable before starting pudb

### ISSUE THREAD

**Issue by j0niy** [inducer/pudb#416]
Hi guys!
I'm currently running into an issue, while trying to start a remote debug.
I am trying to start it with setting the PUDB_TTY variable. This works when I send it with the same command that launches pudb via ssh. The problem here is, that I am working on an IBM i with pase. Which thinks the PUDB_TTY=/dev/pts/1 is the program it has to launch, but obviously can't find it.
So now I need a way to set the variable beforehand, I have tried just sending it before and then starting pudb but that won't work.

Any ideas on that?

Thanks in advance!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. Thanks!

**Comment by j0niy** [comment]
sorry did not see the mailing list first, thank you!
