### ISSUE TITLE
Piping input to script to be debugged leads to TypeError

### ISSUE THREAD

**Issue by makrobios** [inducer/pudb#423]
I am wondering if this is possible with pudb or if there is a workaround. I try to debug a script
that gets its input from stdin over a pipe like this:

`cat input.txt | python script.py`

I already tried to set `PYTHONBREAKPOINT=pudb.forked.set_trace` but i always get the error:

```TypeError: ord() expected a character, but string of length 0 found.```

**Comment by inducer** [comment]
No, pudb expects stdin to be a pty.

**Comment by makrobios** [comment]
Meanwhile I found this to work: 
```
read = sys.stdin.readlines() 
sys.stdin = open("/dev/tty")
breakpoint()
```
