### ISSUE TITLE
auto maximize the sidebar  or the shell while active

### ISSUE THREAD

**Issue by sisrfeng** [inducer/pudb#428]
Hi, could you please tell me how to auto maximize the sidebar  or the shell while active? 
Now if I toggle between code and variables bar, I need to press

> shit+v    ,  shit+=   ,           shit+-    ,        shit+c

If I can set to auto maximize the sidebar, I just need to press
> shit+v     ,  shit+c

Thx!

**Comment by inducer** [comment]
That's not a change I think would be useful. You could write code to do this in your own fork.

**Comment by sisrfeng** [comment]
Would you mind telling me how to change it? I think some combination of shortcut can work,  but can not find the code. 
Thank you very much~
