### ISSUE TITLE
pudb not showing the application modules

### ISSUE THREAD

**Issue by averri** [inducer/pudb#456]
I'm starting a debug session using a `breakpoint()` on my code, and using `export PYTHONBREAKPOINT=pudb.set_trace` before starting the program. 

pudb is not showing my application modules when I press **m** in the main pudb window.

How to set pudb to show my application modules? I'm starting the application from the root directory that contains all the application modules.

**Comment by inducer** [comment]
Just make sure to import all modules you would like to be listed before the breakpoint.

**Comment by averri** [comment]
Hi @inducer, thank you for your reply. I think having to import all modules before the `breakpoint()` is not clean.

I would like to have something like `pdb`, wich shows all the modules listed in the `sys.path`. I see that `pudb` is showing modules for all paths on my `sys.path`, except the application modules. Why is this happening?

Please see my `sys.path`, printed inside the `pudb` shell:

```bash
>>> import sys                                                                                                                          
>>> sys.path                                                                                                                            
['/home/alex/dev/src/my-app', '/home/alex/dev/src/my-app/test/features',                                        
'/home/alex/dev/src/my-app/.venv/bin', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload',     
'/home/alex/dev/src/my-app/.venv/lib/python3.7/site-packages']
```

I can't see any modules from `/home/alex/dev/src/my-app/*`.

**Comment by inducer** [comment]
What `pdb` command shows you this list of modules you speak of? `pudb` shows what's in `sys.modules` FWIW.

**Comment by averri** [comment]
`pdb` shows the list of modules when we add a breakpoint, type the first letters of module and press `tab`.
Are you sure that `pdb` shows the modules listed in `sys.modules`? I have printed the contents of `sys.modules` in the `pdb` shell and it does not list the application modules, but it completes the modules like I mentioned before.

Anyway, I think the workaround for `pudb` is to put the `breakpoint()` in the point where the relevant application modules have been imported.

**Comment by averri** [comment]
I'm closing because the workaround works.

**Comment by averri** [comment]
Thank you @inducer.
