### ISSUE TITLE
quit() exits with an exception

### ISSUE THREAD

**Issue by dtd41** [inducer/pudb#457]
For me, FreeBSD 12.2-RELEASE-p4 and py37-pudb-2020.1 this universal. I tried stepping through the code and it looked to me like very early in the process it might be possible to say, "well we are done, so lets quit" Sadly understanding the what and whys here are way beyond me. I only post this because as I convert 2.7 --> 3.7 I keep getting hung up on this.

From the most resent program:

Traceback (most recent call last):                                   < Clear  > 
  File "/usr/local/bin/pudb3", line 11, in <module>
    load_entry_point('pudb==2020.1', 'console_scripts', 'pudb3')()
  File "/usr/local/lib/python3.7/site-packages/pudb/run.py", line 57, in main
    runscript(mainpyfile, **options_kwargs)
  File "/usr/local/lib/python3.7/site-packages/pudb/__init__.py", line 208, in runscript
    ("esc", "examine"),
  File "/usr/local/lib/python3.7/site-packages/pudb/debugger.py", line 2268, in call_with_ui
    self.show()
  File "/usr/local/lib/python3.7/site-packages/pudb/debugger.py", line 2259, in show
    self.screen.start()
  File "/usr/local/lib/python3.7/site-packages/urwid/display_common.py", line 813, in start
    self._start(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/urwid/raw_display.py", line 227, in _start
    fd = self._input_fileno()
  File "/usr/local/lib/python3.7/site-packages/urwid/raw_display.py", line 98, in _input_fileno
    return self._term_input_file.fileno()
ValueError: I/O operation on closed file

The code:

for values in line:
  rec=dict(list(zip(fields,values)))
  if values[0]=='Date': continue
  val[0]='"'+rec['date']+'"'
  val[1]=str(int(rec['num']))
  val[2]='"'+rec['info'].title()+'"'
  val[3]=rec['amount']
  val[4]='"'+rec['comment']+'"'
  val[5]=rec['code']
  val[6]=rec['PF']
  
  val[2]=re.sub(r'\ +',r' ',val[2])    #remove extra blanks
  val[2]=re.sub(r'^\ +',r'',val[2])
  
  x=','.join(val)+');'
  insertStmt='insert into suntrx values ('+x

  try:
    c.execute(insertStmt)
    
  except Exception as e:
    print(insertStmt)
    print (repr(e))
    break

db.close()
f.close()
quit() 

This runs and executes normally when from from the shell

**Comment by inducer** [comment]
Use `sys.exit()` instead. That'll raise an exception that pudb handles. If you've got a great reason why `quit()` should be preferred (I can't even find documentation on it: https://docs.python.org/3/search.html?q=quit&check_keywords=yes&area=default), feel free to speak up.

**Comment by dtd41** [comment]
Nah, no reason except when I went to a python course it said use quit(). 
sys.exit() works for me, Close the ticket as far as I'm concerned. Thanks 
for the quick response.

You've no idea how much easier (my python) life is with pudb.

Doug


On Wed, 23 Jun 2021, Andreas Kl?ckner wrote:

> 
> Use sys.exit() instead. That'll raise an exception that pudb handles. If you've got a
> great reason why quit() should be preferred (I can't even find documentation on it:
> https://docs.python.org/3/search.html?q=quit&check_keywords=yes&area=default), feel free
> to speak up.
> 
> ?
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AICXMCR7N5QV5WRN2ZUJKE3TUILQDA5CNFSM47GIAKYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW
> 63LNMVXHJKTDN5WW2ZLOORPWSZGOGOW5GKQ.gif]
> 
> 
>

_____
Douglas Denault
http://www.safeport.com
***@***.***
Voice: 301-217-9220
   Fax: 301-217-9277

**Comment by asmeurer** [comment]
Looks like quite closes stdin first, because IDLE requires that, but it breaks pudb. 

Actually, if I type `quit` in the console, it works fine. It's only `quit()` in a file that doesn't work. But you generally should not type quit() in a file. Either let the file just exit, or if you really want to kill the process, use sys.exit(). quit is only designed for exiting the interactive interpreter.

**Comment by dtd41** [comment]
I am fine with use sys.exit(). I did it works. Close it as far as I am 
concerned.

On Wed, 23 Jun 2021, Aaron Meurer wrote:

> 
> Looks like quite closes stdin first, because IDLE requires that, but it breaks pudb.
> 
> Actually, if I type quit in the console, it works fine. It's only quit() in a file that
> doesn't work. But you generally should not type quit() in a file. Either let the file just
> exit, or if you really want to kill the process, use sys.exit(). quit is only designed for
> exiting the interactive interpreter.
> 
> ?
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, orunsubscribe.[AICXMCXEPR3EPECJ47CDMXLTUIZXHA5CNFSM47GIAKYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW
> 63LNMVXHJKTDN5WW2ZLOORPWSZGOGOXPZNQ.gif]
> 
> 
>

_____
Douglas Denault
http://www.safeport.com
***@***.***
Voice: 301-217-9220
   Fax: 301-217-9277
