### ISSUE TITLE
ptpython: unrecognized arguments

### ISSUE THREAD

**Issue by pbsds** [inducer/pudb#509]
When i try to use ptpython as the external shell, it seems to inherit the `argv`, which makes it crash ?

```
$ ./myapp.py --foo --bar --baz
myapp.py: error: unrecognized arguments: --foo --bar --baz
```

**Versions**

What version of pudb? What version of Python?

python: 3.9
pudb: 2022.1
ptpython: 3.0.20

**Comment by inducer** [comment]
Thanks for the report! #510 ought to fix this, LMK if not.

**Comment by jsivak** [comment]
I was seeing the same problem. The changes in #510 fix the issue. Thanks!

**Comment by inducer** [comment]
https://pypi.org/project/pudb/2022.1.1/
