### ISSUE TITLE
Nord Theme

### ISSUE THREAD

**Issue by jgarte** [inducer/pudb#567]
**Is your feature request related to a problem? Please describe.**

I'd like to have a pudb theme similar to this one: 

https://github.com/arcticicestudio/nord-vim
https://www.nordtheme.com/ports/tmux
https://www.nordtheme.com/

**Describe the solution you'd like**

I'd like to have a nord theme.

**Comment by inducer** [comment]
Thanks for the suggestion. I'd be happy to consider a PR contributing this.
