### ISSUE TITLE
"Falling back to custom shell" message printed in internal shell console

### ISSUE THREAD

**Issue by asmeurer** [inducer/pudb#573]
When the custom shell is not installed, pudb automatically fallsback to the classic Python shell. But the message for this is printed in the internal shell console. This is useless because this isn't shown when the shell is active. It should be printed to the terminal. I think this used to be the case, so this likely was changed at some point.

**Comment by asmeurer** [comment]
I think this was changed in 84ed1e31, CC @mvanderkamp

**Comment by mvanderkamp** [comment]
Hmm I wonder if we can actually print it to the python shell.
