### ISSUE TITLE
Greyscale Theme

### ISSUE THREAD

**Issue by jgarte** [inducer/pudb#611]
**Is your feature request related to a problem? Please describe.**

I'd like to request a grey scale theme that looks like eink displays. Mono is not grey scale, for example.

**Describe the solution you'd like**

Something like this emacs color theme:

https://github.com/gugod/grey-paper-theme#screenshots

**Comment by inducer** [comment]
I'd be happy to consider a PR.

**Comment by jgarte** [comment]
I'm not sure if I'm the person to implement this. I just had the idea ;()

**Comment by mvanderkamp-cmb** [comment]
I've been AFK here for a while, maybe I'll take a crack at this and polish up #572.

**Comment by jgarte** [comment]
@mvanderkamp That would be amazing to get those two in. I don't have the time at the moment but feel free to take those tickets over.

**Comment by mvanderkamp** [comment]
k. Just confirming that you're fine with me pushing to the nord branch in your fork?

**Comment by jgarte** [comment]
Yes, definitely. Go for it
