### ISSUE TITLE
export PUDB_TTY=... not working

### ISSUE THREAD

**Issue by ElBartel** [inducer/pudb#634]
Diverting the debugger interface to a diffent tty by setting the PUDB_TTY environment variable does not work.

Simply try:
  `touch any-script.py;
  PUDB_TTY=$(tty) python -mpudb any-script.py`

This results in a `ValueError: I/O operation on closed file.` exception.

This is due to calling `tty_file.close() `   in `_get_debugger()` introduced in [Close tty file when dne querying terminal info](https://github.com/inducer/pudb/commit/277980e92e9e3bac8325387d8f45f509dd597264))
The prolblem is not present, when this call does not happen.

**Comment by inducer** [comment]
Probably fixed by #656. Let me know if that's not the case.
