### ISSUE TITLE
2024.1 display clobbered with internal pudb [DEBUG] messages.

### ISSUE THREAD

**Issue by cederom** [inducer/pudb#649]
**Describe the bug**
* On macOS for some reason pudb seems to use DEBUG loglevel. I could not find any info on how to disable that.
* This results in display being clobbered with internal pudb [DEBUG] messages (i.e. pudb waited for something etc).
* This happens when navigating over the code, variables, etc - [DEBUG] messages of pudb are displayed over the debugger screen making things unreadable.

**To Reproduce**
1. Create python venv.
2. pip install pudb.
3. insert import pudb; pu.db in your application.
4. run the application trigger the debugger.
5. see that each arrow key press results in additional [DEBUG] messages overwriting the screen.

**Expected behavior**
* No [DEBUG] messages shows up so pudb can be used.

**Screenshots**
<img width="480" alt="pudb-problem-20240429" src="https://github.com/inducer/pudb/assets/3051832/d6cbd88a-9255-4945-9c6e-9d8eee6c5490">

**Additional context**
* No problem like this on FreeBSD.

**Versions**
* pudb 2024.1 (also tried with recent master and previous releases no change).
* Python 3.11.9.
* macOS 14.4.1.
* brew 4.2.19-131.

**Comment by inducer** [comment]
That's a fair point. We should probably call [`catch_warnings`](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings) on entry to the UI, then `resetwarnings`, and then override `showwarning` to direct Pudb's own log messages to its built-in console.

PRs implementing this would be welcome.

**Comment by cederom** [comment]
Ot just add `--log-level` switch / setting? :-)

**Comment by inducer** [comment]
I mean, we really need to keep pudb's log level separate from that of the application, despite both of them running with the same Python runtime.

**Comment by inducer** [comment]
Huh, I just realized I am talking about warnings, while you are talking about logging. The two are distinct, and both need handling.

**Comment by inducer** [comment]
#650 handles the warning end of this.

**Comment by cederom** [comment]
Negative :-( still here :-( Its like loglevel DEBUG is enabled somehow o_O

<img width="800" alt="pudb-problem-20240429-2" src="https://github.com/inducer/pudb/assets/3051832/b248d6ca-4910-41b5-8e05-b3f4fced0e6f">

**Comment by inducer** [comment]
Sure. #650 was never going to help with logging, only warnings, sorry. PRs still welcome.

**Comment by cederom** [comment]
Is there a loglevel already implemented anyhow or needs implementation? Where to start?

**Comment by cederom** [comment]
Okay, this is caused by the Kivy framework that I use attaching to a root logger by default [1] thus also capturing pudb logger that also seems to attach to the root logger. Quck fix is to use `PYTHON` or `MIXED` mode when working with pudb.

[1] https://github.com/kivy/kivy/blob/4a8caf561c37944a21bc004bf8faae2d8237e8a1/kivy/logger.py#L78

**Comment by pjkersten** [comment]
Ran into this while debugging a Flask app on linux. Would it be possible to ignore the logger.basicConfig settings to prevent this from happening?

**Comment by cederom** [comment]
> Ran into this while debugging a Flask app on linux. Would it be possible to ignore the logger.basicConfig settings to prevent this from happening?

The problem is using root logger by both pudb and your application. In my case (Kivy) it was possible to change application behavior not to capture and dump everything from the root logger (see description above). That solved clobbered display for me. I guess Flash can be configured in a similar way but I have no experience with Flash sorry.

I guess the best solution would be setting up some sort of internal logger (handler) deidacted for pudb and use its output only in built-in console.
