### ISSUE TITLE
Improve breakpoints view

### ISSUE THREAD

**Issue by inducer** [inducer/pudb#92]
@asmeurer said in #90: (since moved from there to here)

> I actually realized that the breakpoints view could use some work anyway. I've never been a big user of breakpoints, though so I haven't noticed these before. There should be a visual indication on the breakpoint if it is active or not (I'm thinking some character in the already empty space to the left of each breakpoint). A keyboard shortcut to disable a breakpoint without deleting it would be useful, and a keyboard shortcut to jump to the location might be nice too. Any thoughts on this?  
> 
> I'm thinking:
> - `*` (to the left of a breakpoint) means it is active
> - `s` (to the left of the breakpoint, next to the `*`) means it is a `set_trace` breakpoint. We could put other letters there too to indicate state about the breakpoint if it's useful.
> - `b` (?) disables/enables the breakpoint. Maybe another key is better, but this matches the key used in the code view.
> - `l` jumps to the location of the breakpoint (also not sure about this, so feel free to suggest something better. Maybe `L` is better since that matches the "goto" function in the code).

**Comment by fdevibe** [comment]
OK, only saw this one after I added PR #326, so maybe this is unwanted. However, I didn't see how to achieve this until I read this issue, and I would really like a direct route to the file:line in question. I don't care much about which character is used, though.

**Comment by mvanderkamp** [comment]
This can be closed, no? Only feature not present is the `set_trace` distinction which I don't think is important or really all that useful.

**Comment by inducer** [comment]
I'd say so. Thanks for your work towards this! If anyone disagrees, please speak up.
